# espanso match file
# For a complete introduction, visit the official docs at: https://espanso.org/docs/

matches:
  # Work and Personal email and contact information
  # Used for emails, calendaly, etc

  - trigger: ":myie"
    replace: "vincentkoc@ieee.org"

  # Miscellaneous functions
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y"