# espanso match file
# For a complete introduction, visit the official docs at: https://espanso.org/docs/

matches:

  # Miscellaneous functions
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y"

# All other matches see the ./packages (imported) and ./custom (personal) configurations